"""Bulk-enrich instrument sectors in the seed DB."""
import sys
sys.path.insert(0, ".")

import backend.app.services.db as db
db.DB_PATH = db.SEED_DB_PATH

SECTOR_MAP = {
    "PRAJIND": ("Industrials", "Engineering"),
    "IDFCFIRSTB": ("Financials", "Banks"),
    "BORORENEW": ("Utilities", "Renewable Energy"),
    "IEX": ("Financials", "Exchanges"),
    "TIPSINDLTD": ("Communication Services", "Entertainment"),
    "TATAMOTORS": ("Consumer Discretionary", "Automobiles"),
    "ITC": ("Consumer Staples", "Tobacco & FMCG"),
    "XELPMOC": ("Technology", "IT Services"),
    "TRIDENT": ("Consumer Discretionary", "Textiles"),
    "MAPMYINDIA": ("Technology", "Software"),
    "HBLPOWER": ("Industrials", "Electrical Equipment"),
    "BHEL": ("Industrials", "Heavy Electrical"),
    "LXCHEM": ("Materials", "Chemicals"),
    "DCMSRIND": ("Materials", "Chemicals"),
    "IREDA": ("Financials", "Financial Services"),
    "KPITTECH": ("Technology", "IT Services"),
    "HFCL": ("Technology", "Telecom Equipment"),
    "HAPPSTMNDS": ("Technology", "IT Services"),
    "TEJASNET": ("Technology", "Telecom Equipment"),
    "ASHOKLEY": ("Industrials", "Commercial Vehicles"),
    "JIOFIN": ("Financials", "Financial Services"),
    "TATACHEM": ("Materials", "Chemicals"),
    "MTARTECH": ("Industrials", "Precision Engineering"),
    "ZENSARTECH": ("Technology", "IT Services"),
    "DWARKESH": ("Consumer Staples", "Sugar"),
    "EXIDEIND": ("Consumer Discretionary", "Auto Components"),
    "IRCTC": ("Industrials", "Railways"),
    "SAIL": ("Materials", "Steel"),
    "LAURUSLABS": ("Healthcare", "Pharmaceuticals"),
    "MAHABANK": ("Financials", "Banks"),
    "INFY": ("Technology", "IT Services"),
    "RELIANCE": ("Energy", "Oil & Gas"),
    "TCS": ("Technology", "IT Services"),
    "HDFCBANK": ("Financials", "Banks"),
    "SBIN": ("Financials", "Banks"),
    "WIPRO": ("Technology", "IT Services"),
    "TATASTEEL": ("Materials", "Steel"),
    "ADANIPORTS": ("Industrials", "Port Services"),
    "BHARTIARTL": ("Communication Services", "Telecom"),
    "AXISBANK": ("Financials", "Banks"),
    "KOTAKBANK": ("Financials", "Banks"),
    "HINDUNILVR": ("Consumer Staples", "FMCG"),
    "ASIANPAINT": ("Materials", "Paints"),
    "SUNPHARMA": ("Healthcare", "Pharmaceuticals"),
    "MARKSANS": ("Healthcare", "Pharmaceuticals"),
    "LT": ("Industrials", "Construction"),
    "NTPC": ("Utilities", "Power Generation"),
    "COALINDIA": ("Energy", "Mining"),
    "ONGC": ("Energy", "Oil & Gas"),
    "IOC": ("Energy", "Oil & Gas"),
    "BPCL": ("Energy", "Oil & Gas"),
    "PFC": ("Financials", "Financial Services"),
    "RECLTD": ("Financials", "Financial Services"),
    "BANKBARODA": ("Financials", "Banks"),
    "PNB": ("Financials", "Banks"),
    "UNIONBANK": ("Financials", "Banks"),
    "INDUSINDBK": ("Financials", "Banks"),
    "YESBANK": ("Financials", "Banks"),
    "SOUTHBANK": ("Financials", "Banks"),
    "UCOBANK": ("Financials", "Banks"),
    "CANBK": ("Financials", "Banks"),
    "AUBANK": ("Financials", "Banks"),
    "RBLBANK": ("Financials", "Banks"),
    "KARURVYSYA": ("Financials", "Banks"),
    "M&M": ("Consumer Discretionary", "Automobiles"),
    "M&MFIN": ("Financials", "NBFC"),
    "HDFCLIFE": ("Financials", "Insurance"),
    "BAJAJHFL": ("Financials", "Housing Finance"),
    "LICI": ("Financials", "Insurance"),
    "STARHEALTH": ("Financials", "Insurance"),
    "ISEC": ("Financials", "Broking"),
    "CAMS": ("Financials", "Financial Services"),
    "HAL": ("Industrials", "Defence"),
    "HINDALCO": ("Materials", "Metals"),
    "HINDZINC": ("Materials", "Metals"),
    "HINDCOPPER": ("Materials", "Metals"),
    "NATIONALUM": ("Materials", "Metals"),
    "NMDC": ("Materials", "Mining"),
    "DLF": ("Real Estate", "Real Estate"),
    "BRIGADE": ("Real Estate", "Real Estate"),
    "KOLTEPATIL": ("Real Estate", "Real Estate"),
    "GMRINFRA": ("Industrials", "Infrastructure"),
    "IRCON": ("Industrials", "Construction"),
    "RVNL": ("Industrials", "Railways"),
    "NHPC": ("Utilities", "Power Generation"),
    "SJVN": ("Utilities", "Power Generation"),
    "ADANIPOWER": ("Utilities", "Power Generation"),
    "SUZLON": ("Utilities", "Renewable Energy"),
    "INDUSTOWER": ("Communication Services", "Telecom"),
    "IDEA": ("Communication Services", "Telecom"),
    "MTNL": ("Communication Services", "Telecom"),
    "ZOMATO": ("Consumer Discretionary", "Food Delivery"),
    "ETERNAL": ("Consumer Discretionary", "Food Delivery"),
    "NYKAA": ("Consumer Discretionary", "E-Commerce"),
    "DMART": ("Consumer Staples", "Retail"),
    "TRENT": ("Consumer Discretionary", "Retail"),
    "INDIGO": ("Industrials", "Airlines"),
    "SPICEJET": ("Industrials", "Airlines"),
    "BIOCON": ("Healthcare", "Pharmaceuticals"),
    "TECHM": ("Technology", "IT Services"),
    "NAZARA": ("Technology", "Gaming"),
    "LATENTVIEW": ("Technology", "IT Services"),
    "PIDILITIND": ("Materials", "Chemicals"),
    "BERGEPAINT": ("Materials", "Paints"),
    "AMBUJACEM": ("Materials", "Cement"),
    "JSWSTEEL": ("Materials", "Steel"),
    "TATAELXSI": ("Technology", "IT Services"),
    "TATATECH": ("Technology", "IT Services"),
    "TATACONSUM": ("Consumer Staples", "FMCG"),
    "DABUR": ("Consumer Staples", "FMCG"),
    "MARICO": ("Consumer Staples", "FMCG"),
    "BALRAMCHIN": ("Consumer Staples", "Sugar"),
    "MAWANASUG": ("Consumer Staples", "Sugar"),
    "BODALCHEM": ("Materials", "Chemicals"),
    "ALKYLAMINE": ("Materials", "Chemicals"),
    "BALAMINES": ("Materials", "Chemicals"),
    "DEEPAKNTR": ("Materials", "Chemicals"),
    "CENTURYTEX": ("Consumer Discretionary", "Textiles"),
    "UPL": ("Materials", "Agrochemicals"),
    "RAIN": ("Materials", "Chemicals"),
    "GRAPHITE": ("Materials", "Carbon Products"),
    "OIL": ("Energy", "Oil & Gas"),
    "GSFC": ("Materials", "Fertilizers"),
    "NFL": ("Materials", "Fertilizers"),
    "PARADEEP": ("Materials", "Fertilizers"),
    "POONAWALLA": ("Financials", "NBFC"),
    "SHEMAROO": ("Communication Services", "Entertainment"),
    "DISHTV": ("Communication Services", "Media"),
    "ZEEL": ("Communication Services", "Media"),
    "NAUKRI": ("Technology", "Internet"),
    "CAMPUS": ("Consumer Discretionary", "Footwear"),
    "RELAXO": ("Consumer Discretionary", "Footwear"),
    "DIXON": ("Technology", "Electronics Manufacturing"),
    "ASTRAL": ("Industrials", "Building Products"),
    "PRINCEPIPE": ("Industrials", "Building Products"),
    "RPOWER": ("Utilities", "Power Generation"),
    "CGPOWER": ("Industrials", "Electrical Equipment"),
    "BIRLACABLE": ("Industrials", "Cables"),
    "BALKRISIND": ("Consumer Discretionary", "Tyres"),
    "MOTHERSON": ("Consumer Discretionary", "Auto Components"),
    "MOTHERSUMI": ("Consumer Discretionary", "Auto Components"),
    "SONACOMS": ("Consumer Discretionary", "Auto Components"),
    "DEVYANI": ("Consumer Discretionary", "QSR"),
    "EASEMYTRIP": ("Consumer Discretionary", "Travel"),
    "DREAMFOLKS": ("Consumer Discretionary", "Travel"),
    "IMAGICAA": ("Consumer Discretionary", "Entertainment"),
    "GREAVESCOT": ("Industrials", "Engineering"),
    "EXICOM": ("Industrials", "EV Charging"),
    "PCBL": ("Materials", "Carbon Black"),
    "ACRYSIL": ("Consumer Discretionary", "Kitchen Products"),
    "PATANJALI": ("Consumer Staples", "FMCG"),
    "SHAREINDIA": ("Financials", "Broking"),
    "CUPID": ("Healthcare", "Medical Devices"),
    "ABFRL": ("Consumer Discretionary", "Apparel"),
    "APOLLO": ("Healthcare", "Hospitals"),
    "PVR": ("Consumer Discretionary", "Entertainment"),
    "POWERGRID": ("Utilities", "Power Transmission"),
    "NLCINDIA": ("Utilities", "Power Generation"),
    "ADSL": ("Technology", "IT Services"),
    "BBOX": ("Industrials", "Logistics"),
    "AEGISLOG": ("Industrials", "Logistics"),
    "AEGISCHEM": ("Industrials", "Logistics"),
    "SCI": ("Industrials", "Shipping"),
    "SEPC": ("Industrials", "Construction"),
    "AWL": ("Consumer Staples", "Edible Oil"),
    "KALPATPOWR": ("Industrials", "EPC"),
    "NCC": ("Industrials", "Construction"),
    "HCC": ("Industrials", "Construction"),
    "KEC": ("Industrials", "EPC"),
    "NTPCGREEN": ("Utilities", "Renewable Energy"),
    "GREENPOWER": ("Utilities", "Renewable Energy"),
    "ITI": ("Technology", "Telecom Equipment"),
    "IFCI": ("Financials", "Financial Services"),
    "IDFC": ("Financials", "Financial Services"),
    "INTELLECT": ("Technology", "IT Services"),
    "WOCKPHARMA": ("Healthcare", "Pharmaceuticals"),
    "AMARAJABAT": ("Consumer Discretionary", "Auto Components"),
    "VEDAVAAG": ("Technology", "IT Services"),
    "JAGRAN": ("Communication Services", "Media"),
    "SUBEX": ("Technology", "IT Services"),
    "SUBEXLTD": ("Technology", "IT Services"),
    "MOSCHIP": ("Technology", "Semiconductors"),
    "ALEMBICLTD": ("Healthcare", "Pharmaceuticals"),
    "APLLTD": ("Healthcare", "Pharmaceuticals"),
    "AARTIDRUGS": ("Healthcare", "Pharmaceuticals"),
    "DEEPAKNI": ("Materials", "Chemicals"),
    "DAAWAT": ("Consumer Staples", "Food Products"),
    "HERITGFOOD": ("Consumer Staples", "Food Products"),
    "MANAKSIA": ("Materials", "Packaging"),
    "FSL": ("Technology", "IT Services"),
    "CLEAN": ("Industrials", "Industrial Services"),
    "GODREJIND": ("Materials", "Chemicals"),
    "MOREPENLAB": ("Healthcare", "Pharmaceuticals"),
    "THYROCARE": ("Healthcare", "Diagnostics"),
    "GIPCL": ("Utilities", "Power Generation"),
    "EVEREADY": ("Consumer Staples", "Batteries"),
    "WABAG": ("Industrials", "Water Treatment"),
    "BSOFT": ("Technology", "IT Services"),
    "AVANTIFEED": ("Consumer Staples", "Aquaculture"),
    "GATI": ("Industrials", "Logistics"),
    "GEOJITFSL": ("Financials", "Broking"),
    "POKARNA": ("Materials", "Granite"),
    "ASAL": ("Technology", "IT Services"),
    "IRB": ("Industrials", "Infrastructure"),
    "HUBTOWN": ("Real Estate", "Real Estate"),
    "TATACOMM": ("Communication Services", "Telecom"),
    "HBLENGINE": ("Industrials", "Electrical Equipment"),
    "MAHSEAMLES": ("Materials", "Steel"),
    "PRECWIRE": ("Industrials", "Cables"),
    "PAISALO": ("Financials", "NBFC"),
    "ESAFSFB": ("Financials", "Banks"),
    "DCXINDIA": ("Technology", "IT Services"),
    "HITECH": ("Industrials", "Pipes"),
    "INDOBORAX": ("Materials", "Chemicals"),
    "LINCOLN": ("Healthcare", "Pharmaceuticals"),
    "VIMTALABS": ("Healthcare", "Pharmaceuticals"),
    "PANACEABIO": ("Healthcare", "Pharmaceuticals"),
    "GUFICBIO": ("Healthcare", "Pharmaceuticals"),
    "FDC": ("Healthcare", "Pharmaceuticals"),
    "SUDEEPPHRM": ("Healthcare", "Pharmaceuticals"),
    "DCW": ("Materials", "Chemicals"),
    "DLINKINDIA": ("Technology", "Networking"),
    "DCMSHRIRAM": ("Materials", "Chemicals"),
    "REDINGTON": ("Technology", "IT Distribution"),
    "TREL": ("Utilities", "Power Transmission"),
    "STLNETWORK": ("Communication Services", "Telecom"),
    "TRIVENI": ("Industrials", "Engineering"),
    "SATINDLTD": ("Consumer Discretionary", "Textiles"),
    "RAJESHEXPO": ("Consumer Staples", "Food Products"),
    "GUJALKALI": ("Materials", "Chemicals"),
    "LAOPALA": ("Consumer Discretionary", "Glassware"),
    "PATELENG": ("Industrials", "Construction"),
    "KRBL": ("Consumer Staples", "Food Products"),
    "MEGH": ("Materials", "Chemicals"),
    "ITDCEM": ("Industrials", "Construction"),
    "DALMIASUG": ("Consumer Staples", "Sugar"),
    "PEL": ("Financials", "Financial Services"),
    "KCPSUGIND": ("Consumer Staples", "Sugar"),
    "PASUPTAC": ("Consumer Staples", "Sugar"),
    "LUMAXTECH": ("Consumer Discretionary", "Auto Components"),
    "KABRAEXTRU": ("Industrials", "Machinery"),
    "ANURAS": ("Consumer Discretionary", "QSR"),
    "AERPACE": ("Industrials", "Aerospace"),
    "OSWALGREEN": ("Materials", "Chemicals"),
    "WARDINMOBI": ("Technology", "IT Services"),
    "SRESTHA": ("Consumer Staples", "Food Products"),
    "DBEIL": ("Industrials", "Defence"),
    "BELRISE": ("Consumer Discretionary", "Auto Components"),
    "ENRIN": ("Utilities", "Power"),
    "ENERGYDEV": ("Utilities", "Power"),
    "NIYOGIN": ("Financials", "Fintech"),
    "HARDWYN": ("Industrials", "Building Products"),
    "TDPOWERSYS": ("Industrials", "Electrical Equipment"),
    "TEXRAIL": ("Industrials", "Railways"),
    "PARAGMILK": ("Consumer Staples", "Dairy"),
    "JYOTI": ("Industrials", "Electrical Equipment"),
    "JYOTISTRUC": ("Industrials", "Construction"),
    "CORDSCABLE": ("Industrials", "Cables"),
    "TINPLATE": ("Materials", "Metals"),
    "MCLOUD": ("Technology", "Cloud Computing"),
    "NDL": ("Industrials", "Networking"),
    "TTKPRESTIG": ("Consumer Discretionary", "Kitchen Appliances"),
    "MSUMI": ("Consumer Discretionary", "Auto Components"),
    "MICEL": ("Consumer Staples", "Edible Oil"),
    "ESTER": ("Materials", "Packaging"),
    "MINDTECK": ("Technology", "IT Services"),
    "UJAAS": ("Utilities", "Renewable Energy"),
    "CUBEXTUB": ("Materials", "Metals"),
    "VPRPL": ("Consumer Discretionary", "QSR"),
    "WANBURY": ("Healthcare", "Pharmaceuticals"),
    "RATHIBAR": ("Materials", "Steel"),
    "PARAS": ("Healthcare", "Pharmaceuticals"),
    "BALAJITELE": ("Communication Services", "Entertainment"),
    "RAMKY": ("Industrials", "Infrastructure"),
    "URJA": ("Utilities", "Renewable Energy"),
    "URJAGLOBA": ("Utilities", "Renewable Energy"),
    "SURANASOL": ("Utilities", "Renewable Energy"),
    "SPELS": ("Consumer Discretionary", "Apparel"),
    "EVEXIA": ("Healthcare", "Pharma"),
    "LALPATHLAB": ("Healthcare", "Diagnostics"),
    "POEL": ("Industrials", "Engineering"),
    "GEPIL": ("Industrials", "Engineering"),
    "CEREBRAINT": ("Technology", "IT Services"),
    "INTLCONV": ("Industrials", "Packaging"),
    "INTELSOFT": ("Technology", "IT Services"),
    "RTNINDIA": ("Utilities", "Renewable Energy"),
    "SAPPHIRE": ("Industrials", "Engineering"),
    "RKEC": ("Industrials", "Construction"),
    "PDMJEPAPER": ("Materials", "Paper"),
    "VIRATCRA": ("Industrials", "Engineering"),
    "ATVPR": ("Industrials", "Engineering"),
    "ANDHRAPET": ("Materials", "Chemicals"),
    "RGL": ("Consumer Staples", "Food Products"),
    "ALKALI": ("Materials", "Chemicals"),
    "MANALIPETC": ("Materials", "Chemicals"),
    "DPSCLTD": ("Technology", "IT Services"),
    "MANGIND": ("Materials", "Chemicals"),
    "MANAKSTEEL": ("Materials", "Steel"),
    "SWANENERGY": ("Utilities", "Power"),
    "RELINFRA": ("Industrials", "Infrastructure"),
    "QUICKHEAL": ("Technology", "Cybersecurity"),
    "BIRLAPREC": ("Industrials", "Engineering"),
    "WEBELSOLAR": ("Utilities", "Renewable Energy"),
    "MSTCLTD": ("Industrials", "E-Commerce"),
    "MSTC": ("Industrials", "E-Commerce"),
    "VIJAYA": ("Consumer Staples", "Food Products"),
    "MISHTANN": ("Consumer Staples", "Food Products"),
    "TIPSFILMS": ("Communication Services", "Entertainment"),
    "ALFATRAN": ("Industrials", "Transformers"),
    "L&TFH": ("Financials", "NBFC"),
    "GAEL": ("Consumer Staples", "Edible Oil"),
    "GPPL": ("Utilities", "Power Generation"),
    "PTC": ("Utilities", "Power Trading"),
    "RBLBANK": ("Financials", "Banks"),
    "TIPSMUSIC": ("Communication Services", "Entertainment"),
    "SAREGAMA": ("Communication Services", "Entertainment"),
}

conn = db.get_connection()
c = conn.cursor()

enriched = 0
for sym, (sector, industry) in SECTOR_MAP.items():
    c.execute(
        "UPDATE instruments SET sector=?, industry=? WHERE symbol=? AND (sector IS NULL OR sector = '')",
        (sector, industry, sym),
    )
    enriched += c.rowcount

conn.commit()

c.execute("SELECT COUNT(*) FROM instruments WHERE sector IS NOT NULL AND sector != ''")
with_sector = c.fetchone()[0]
c.execute("SELECT COUNT(*) FROM instruments")
total = c.fetchone()[0]
conn.close()

print(f"Enriched {enriched} instrument rows")
print(f"Final: {with_sector}/{total} instruments have sectors ({round(with_sector/total*100)}%)")
